apiVersion: v1
kind: Service
metadata:
  name: zot
  namespace: tooling
spec:
  selector:
    # This MUST match the labels in your Zot Deployment/StatefulSet
    app.kubernetes.io/name: zot 
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

